version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/firebridge"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/firebridge/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_firebridge"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_firebridge/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/firebridge/native"
    schedule:
      interval: weekly
